#!/usr/bin/env node
/**
 * Generates add_curriculum_data.sql from the JSON export files.
 *
 * Usage:
 *   node migrations/generate_curriculum_data.js
 *
 * This reads each JSON file in Curriculum/exports/ and produces
 * a single SQL file with INSERT statements for all curriculum data.
 */

const fs = require("fs");
const path = require("path");

const EXPORTS_DIR = path.join(__dirname, "..", "Curriculum", "exports");
const OUTPUT_FILE = path.join(__dirname, "add_curriculum_data.sql");

function esc(val) {
  if (val === null || val === undefined) return "NULL";
  if (typeof val === "boolean") return val ? "TRUE" : "FALSE";
  if (typeof val === "number") return String(val);
  if (Array.isArray(val) || typeof val === "object") return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
  return `'${String(val).replace(/'/g, "''")}'`;
}

function loadJSON(filename) {
  const filepath = path.join(EXPORTS_DIR, filename);
  if (!fs.existsSync(filepath)) return [];
  const data = JSON.parse(fs.readFileSync(filepath, "utf-8"));
  return Array.isArray(data) ? data : [];
}

function generateInserts(tableName, rows, columnMap) {
  if (rows.length === 0) return "";

  const columns = Object.keys(columnMap);
  const colNames = columns.map((c) => columnMap[c]).join(", ");
  const lines = [`-- ${tableName}: ${rows.length} records`];
  lines.push(`DELETE FROM ${tableName};`);

  // Batch in groups of 50 to avoid overly long statements
  for (let i = 0; i < rows.length; i += 50) {
    const batch = rows.slice(i, i + 50);
    const values = batch.map((row) => {
      const vals = columns.map((jsonKey) => esc(row[jsonKey]));
      return `  (${vals.join(", ")})`;
    });
    lines.push(`INSERT INTO ${tableName} (${colNames}) VALUES`);
    lines.push(values.join(",\n") + ";");
  }

  return lines.join("\n") + "\n\n";
}

// ── Build the SQL ────────────────────────────────────────────

let sql = `-- ============================================================
-- Migration: Curriculum Data
-- Populates all curriculum tables with OECS curriculum data.
-- Run AFTER add_curriculum_tables.sql.
--
-- Generated by: node migrations/generate_curriculum_data.js
-- ============================================================

BEGIN;

`;

// 1. Spine strands (must be first — referenced by ELOs and SCOs)
sql += generateInserts("curriculum_spine_strands", loadJSON("spine_strands.json"), {
  id: "id",
  subject_id: "subject_id",
  grade_id: "grade_id",
  subject_name: "subject_name",
  subject_slug: "subject_slug",
  grade_level: "grade_level",
  strand_name: "strand_name",
  strand_order: "strand_order",
  created_at: "created_at",
});

// 2. Spine ELOs (references strands)
sql += generateInserts("curriculum_spine_elos", loadJSON("spine_elos.json"), {
  id: "id",
  strand_id: "strand_id",
  elo_text: "elo_text",
  elo_order: "elo_order",
  created_at: "created_at",
});

// 3. Spine SCOs (references ELOs and strands)
sql += generateInserts("curriculum_spine_scos", loadJSON("spine_scos.json"), {
  id: "id",
  elo_id: "elo_id",
  strand_id: "strand_id",
  subject_id: "subject_id",
  subject_slug: "subject_slug",
  grade_id: "grade_id",
  grade_level: "grade_level",
  strand_name: "strand_name",
  sco_text: "sco_text",
  sco_order: "sco_order",
  integrated_units: "integrated_units",
  created_at: "created_at",
});

// 4. Activities
sql += generateInserts("curriculum_activities", loadJSON("curriculum_activities.json"), {
  id: "id",
  subject: "subject",
  grade_level: "grade_level",
  strand: "strand",
  elo_number: "elo_number",
  activity_number: "activity_number",
  title: "title",
  description: "description",
  activity_type: "activity_type",
  materials: "materials",
  integration_subjects: "integration_subjects",
  difficulty_level: "difficulty_level",
  duration_minutes: "duration_minutes",
  group_size: "group_size",
  sort_order: "sort_order",
  created_at: "created_at",
  updated_at: "updated_at",
});

// 5. Assessment strategies
sql += generateInserts("curriculum_assessment_strategies", loadJSON("curriculum_assessment_strategies.json"), {
  id: "id",
  subject: "subject",
  grade_level: "grade_level",
  strand: "strand",
  elo_number: "elo_number",
  strategy_type: "strategy_type",
  strategy_category: "strategy_category",
  description: "description",
  sort_order: "sort_order",
  created_at: "created_at",
  updated_at: "updated_at",
});

// 6. Media resources
sql += generateInserts("curriculum_media_resources", loadJSON("curriculum_media_resources.json"), {
  id: "id",
  subject: "subject",
  grade_level: "grade_level",
  strand: "strand",
  elo_number: "elo_number",
  resource_type: "resource_type",
  title: "title",
  url: "url",
  description: "description",
  sort_order: "sort_order",
  created_at: "created_at",
  updated_at: "updated_at",
});

// 7. ELO metadata
sql += generateInserts("curriculum_elo_metadata", loadJSON("curriculum_elo_metadata.json"), {
  id: "id",
  subject: "subject",
  grade_level: "grade_level",
  strand: "strand",
  elo_number: "elo_number",
  elo_title: "elo_title",
  elo_description: "elo_description",
  grade_expectations: "grade_expectations",
  created_at: "created_at",
  updated_at: "updated_at",
});

// 8. Learning standards
sql += generateInserts("curriculum_learning_standards", loadJSON("learning_standards.json"), {
  id: "id",
  code: "code",
  description: "description",
  subject: "subject",
  grade_level: "grade_level",
  strand: "strand",
  strand_code: "strand_code",
  sub_strand: "sub_strand",
  sub_strand_code: "sub_strand_code",
  domain: "domain",
  grade_grouping: "grade_grouping",
  standard_number: "standard_number",
  created_at: "created_at",
  updated_at: "updated_at",
});

// 9. Legacy strands
sql += generateInserts("curriculum_legacy_strands", loadJSON("strands.json"), {
  id: "id",
  code: "code",
  name: "name",
  description: "description",
  subject: "subject",
  grade_level: "grade_level",
  sort_order: "sort_order",
  is_active: "is_active",
  created_at: "created_at",
  updated_at: "updated_at",
});

// 10. Legacy ELOs
sql += generateInserts("curriculum_legacy_elos", loadJSON("essential_learning_outcomes.json"), {
  id: "id",
  strand_id: "strand_id",
  code: "code",
  description: "description",
  grade_expectations: "grade_expectations",
  sort_order: "sort_order",
  is_active: "is_active",
  created_at: "created_at",
  updated_at: "updated_at",
});

// 11. Legacy SCOs (generate IDs since source has null IDs)
const legacyScos = loadJSON("specific_curriculum_outcomes.json").map((row, i) => ({
  ...row,
  id: row.id || `legacy-sco-${i + 1}`,
}));
sql += generateInserts("curriculum_legacy_scos", legacyScos, {
  id: "id",
  elo_id: "elo_id",
  subject: "subject",
  grade_level: "grade_level",
  strand: "strand",
  code: "code",
  description: "description",
  sub_strand: "sub_strand",
  sub_strand_number: "sub_strand_number",
  elo_title: "elo_title",
  elo_number: "elo_number",
  outcome_type: "outcome_type",
  section: "section",
  theme: "theme",
  created_at: "created_at",
  updated_at: "updated_at",
});

sql += "COMMIT;\n";

fs.writeFileSync(OUTPUT_FILE, sql, "utf-8");

// Summary
const tables = [
  ["curriculum_spine_strands", loadJSON("spine_strands.json").length],
  ["curriculum_spine_elos", loadJSON("spine_elos.json").length],
  ["curriculum_spine_scos", loadJSON("spine_scos.json").length],
  ["curriculum_activities", loadJSON("curriculum_activities.json").length],
  ["curriculum_assessment_strategies", loadJSON("curriculum_assessment_strategies.json").length],
  ["curriculum_media_resources", loadJSON("curriculum_media_resources.json").length],
  ["curriculum_elo_metadata", loadJSON("curriculum_elo_metadata.json").length],
  ["curriculum_learning_standards", loadJSON("learning_standards.json").length],
  ["curriculum_legacy_strands", loadJSON("strands.json").length],
  ["curriculum_legacy_elos", loadJSON("essential_learning_outcomes.json").length],
  ["curriculum_legacy_scos", legacyScos.length],
];

const total = tables.reduce((sum, [, count]) => sum + count, 0);
console.log(`Generated ${OUTPUT_FILE}`);
console.log(`\nTables:`);
tables.forEach(([name, count]) => console.log(`  ${name}: ${count} records`));
console.log(`\nTotal: ${total} records`);
